name: Tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@main
      - name: Set up Python 3.8
        uses: actions/setup-python@main
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Add tgcnn_act_graph to PYTHONPATH
        run: |
          echo "PYTHONPATH=$env:PYTHONPATH;$($PWD.Path)/tgcnn_act_graph" >> $env:GITHUB_ENV

      - name: Test with pytest
        run: pytest test_graphs/test_calculations.py
